### ISSUE TITLE
Enhancement request: Avoid having to manage the /version#/ segment in URL

### ISSUE THREAD

**Issue by sumurthy** [OneDrive/markdown-scanner#107]
Today, the API samples have version number in the URL as one of the segments. In many instance, that is the only difference between two versions. 
Providing the version information in the API example is error prone. 

Could we eliminate this need somehow? 
- Maybe we don't include version# in the segment at all and just use resource path 
- MD Scanner could update the URL path in the API file based on some configuration setting.

**Comment by rgregg** [comment]
This seems like a request to go in the graph-docs open issues, not the markdown-scanner tool. I'd recommend going with option 1 and removing the version number from the example.
