### ISSUE TITLE
Markdown scanner submodule markdowndeep reference update

### ISSUE THREAD

**Issue by MIchaelMainer** [OneDrive/markdown-scanner#162]
The referenced markdowndeep submodule is maintained here:
https://github.com/rgregg/markdowndeep

We should fork markdowndeep into a blessed location under the OneDrive GH organization, or just use the source markdowndeep repo. 

From https://stackoverflow.com/questions/913701/changing-remote-repository-for-a-git-submodule, this has worked for me in the past:

```
git config --file=.gitmodules -e
// then change the URL to the blessed location.
git submodule sync
git submodule update --init --recursive --remote

```

**Comment by natalieethell** [comment]
I forked markdowndeep into the OneDrive org and changed the reference. Change here: #164
